require('json2ify')
require('es5-shimify')
require('jqueryify')
require('lib/jquery-ui.min')
require('lib/jquery.cookie')
require('lib/jquery.joyride')
require('lib/jquery.ui.touch-punch')

require('spine')
require('spine/lib/local')
require('spine/lib/ajax')
require('spine/lib/manager')
require('spine/lib/route')
